name: urfu_brs_bot

networks:
  urfu_brs_bot:
    external: true

volumes:
  brs_user_service_db:
    external: true
  brs_urfu_service_db:
    external: true

services:
  brs_tg_bot:
    build:
      context: ./BrsTgBot
      dockerfile: ./Dockerfile
    restart: always
    container_name: brs_tg_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
    ports:
      - "8080:8080"
    networks:
      - urfu_brs_bot
  brs_user_service:
    build:
      context: ./UserService
      dockerfile: ./Dockerfile
    restart: always
    container_name: brs_user_service
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING_USER_SERVICE}
    ports:
      - "8081:8080"
    networks:
      - urfu_brs_bot
  brs_user_service_db:
    image: postgres:latest
    restart: always
    container_name: brs_user_service_db
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    ports:
      - "5432:5432"
    volumes:
      - brs_user_service_db:/var/lib/postgresql/data
    networks:
      - urfu_brs_bot
  brs_urfu_service:
    build:
      context: ./UrfuService
      dockerfile: ./Dockerfile
    restart: always
    container_name: brs_urfu_service
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING_URFU_SERVICE}
    ports:
      - "8082:8080"
    networks:
      - urfu_brs_bot
  brs_urfu_service_db:
    image: postgres:latest
    restart: always
    container_name: brs_urfu_service_db
    environment:
      - POSTGRES_USER=${PG_USER_URFU_SERVICE}
      - POSTGRES_PASSWORD=${PG_PASSWORD_URFU_SERVICE}
      - POSTGRES_DB=${PG_DB_URFU_SERVICE}
    ports:
      - "5433:5432"
    volumes:
      - brs_urfu_service_db:/var/lib/postgresql/data
    networks:
      - urfu_brs_bot